### ISSUE TITLE
example dataset for the code

### ISSUE THREAD

**Issue by MeiyuanJi** [Wendellab/CisTransRegulation#4]
Hi,

Can you please upload some example datasets for the code? I have some problem in understanding your code for the inheritance calculation. 

Many thanks in advance!

**Comment by huguanjing** [comment]
The input files for [inheritanceMode.r](https://github.com/Wendellab/CisTransRegulation/blob/master/inheritanceMode.r) are as follows: 
[Genes27816.raw.count.txt](https://github.com/Wendellab/CisTransRegulation/files/5311405/Genes27816.raw.count.txt)
[Genes27816.sample.info.txt](https://github.com/Wendellab/CisTransRegulation/files/5311407/Genes27816.sample.info.txt)

**Comment by MeiyuanJi** [comment]
Thank you so much! 

Meiyuan

**Comment by MeiyuanJi** [comment]
There is a question about what reads count you used for inheritance caculation. Is it the total read count or the allele-specific read count of each gene?

Meiyuan

**Comment by huguanjing** [comment]
Total.
